# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compilation and Installation
      run: bash scripts/build.sh
    - name: push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PUBLISH_DOCS }}
        branch: master
